cmake_minimum_required(VERSION 3.16)
project(sister_vpn LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(OpenSSL REQUIRED)
add_executable(sister-vpn src/main.cpp src/vpn.cpp src/tun.cpp src/udp.cpp src/crypto.cpp)
target_include_directories(sister-vpn PRIVATE includes)
target_compile_options(sister-vpn PRIVATE -Wall -Wextra -Wpedantic -Werror)
target_link_libraries(sister-vpn PRIVATE OpenSSL::Crypto)
